save_interval: 1

train:
  image_size: 64
  steps: 1000
  image_channels: 1
  lr: 0.0002
  beta: [0.0001, 0.02]
  batch_size: 256
  epochs: 100

inf:
  steps: 1000

model:
  base_channels: 64
  timestep_embed_dims: 64
  timestep_proj_dims: 256
  layers: 2

clip: 1.0

device: "cuda:6"